### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by RomanHotsiy** [bswinnerton/nyc-restaurant-grades#3]
Getting `Application error` when trying to open http://nyc-restaurant-grades.com/

**Comment by awkale** [comment]
+1

**Comment by bswinnerton** [comment]
Oops! I'm so sorry, I wasn't watching the repository, so I never received the ping for this issue.

I'm on it.

**Comment by bswinnerton** [comment]
@RomanGotsiy & @awkale, thanks for the report and sorry this took so long to fix. We're back in business.

I've just updated the application to the latest and greatest version of graphql-ruby in 50910b862fa302b0fad51af689cc660774d67660 in case you're interested.
